
const orgNameChildOptions = [
    { value: '', label: 'Chọn ngành' },
    { value: 'Cong nghe Ky thuat dien, dien tu', label: 'Công nghệ Kỹ thuật điện, điện tử' },
    { value: 'Cong nghe Che tao may', label: 'Công nghệ chế tạo máy' },
    { value: 'Cong nghe Ky thuat co dien tu', label: 'Công nghệ Kỹ thuật cơ điện tử' },
    { value: 'Cong nghe Ky thuat co khi', label: 'Công nghệ Kỹ thuật cơ khí' },
    { value: 'Cong nghe Ky thuat Dien tu - Vien thong', label: 'Công nghệ Kỹ thuật Điện tử - Viễn thông' },
    { value: 'Cong nghe Ky thuat Ky thuat o to', label: 'Công nghệ Kỹ thuật ô tô' },
    { value: 'Cong nghe Ky thuat nhiet', label: 'Công nghệ Kỹ thuật nhiệt' },
    { value: 'Cong nghe Ky thuat Dieu khien va Tu dong hoa', label: 'Công nghệ Kỹ thuật Điều khiển và Tự động hóa' },
    { value: 'Robot va tri tue nhan tao', label: 'Robot và trí tuệ nhân tạo' },
    { value: 'Cong nghe Ky thuat May tinh', label: 'Công nghệ Kỹ thuật Máy tính' },
    { value: 'Quan ly cong nghiep', label: 'Quản lý công nghiệp' },
    { value: 'Ke toan', label: 'Kế toán' },
    { value: 'Thuong mai dien tu', label: 'Thương mại điện tử' },
    { value: 'Ky thuat Cong nghiep', label: 'Kỹ thuật Công nghiệp' },
    { value: 'Logistics va quan ly chuoi cung ung', label: 'Logistics và quản lý chuỗi cung ứng' },
    { value: 'Cong nghe thong tin', label: 'Công nghệ Thông tin' },
    { value: 'Ky thuat du lieu', label: 'Kỹ thuật dữ liệu' },
    { value: 'Thiet ke do hoa', label: 'Thiết kế đồ họa' },
    { value: 'Cong nghe May', label: 'Công nghệ May' },
    { value: 'Thiet ke thoi trang', label: 'Thiết kế thời trang' },
    { value: 'Ky thuat Y sinh', label: 'Kỹ thuật Y sinh' },
    { value: 'Cong nghe vat lieu', label: 'Công nghệ vật liệu' },
    { value: 'Cong nghe Ky thuat moi truong', label: 'Công nghệ Kỹ thuật môi trường' },
    { value: 'Cong nghe Thuc pham', label: 'Công nghệ thực phẩm' },
    { value: 'Cong nghe Ky thuat Hoa hoc', label: 'Công nghệ Kỹ thuật Hóa học' },
    { value: 'Kinh te gia dinh', label: 'Kinh tế gia đình' },
    { value: 'Quan tri nha hang va dich vu an uong', label: 'Quản trị nhà hàng & Dịch vụ ăn uống' },
    { value: 'Su pham Anh', label: 'Sư phạm Anh' },
    { value: 'Ngon ngu Anh', label: 'Ngôn ngữ Anh' },
    { value: 'Ky thuat xay dung cong trinh giao thong', label: 'Kỹ thuật Xây dựng công trình Giao thông' },
    { value: 'Cong nghe Ky thuat cong trinh xay dung', label: 'Công nghệ Kỹ thuật công trình Xây dựng' },
    { value: 'Quan li xay dung', label: 'Quản lí xây dựng' },
    { value: 'Kien truc', label: 'Kiến trúc' },
    { value: 'Kien truc noi that', label: 'Kiến trúc nội thất' },
    { value: 'Che bien lam san', label: 'Chế biến lâm sản' },
    { value: 'Ky thuat vat lieu', label: 'Kỹ thuật vật liệu' },
  ];
  
  export default orgNameChildOptions;
  